### ISSUE TITLE
does your school have dyned course?

### ISSUE THREAD

**Issue by blackmaple** [u16rogue/dynmemed#1]

**Comment by u16rogue** [comment]
I'm not sure about it

**Comment by blackmaple** [comment]
I wonder why you wrote this

local cheat?

**Comment by u16rogue** [comment]
Availability, curiousity, and it seemed fun to make

**Comment by blackmaple** [comment]
Why don't you use Win32 API writeprocessmemory

**Comment by u16rogue** [comment]
Because it's loaded into the process as a dynamic library which gives me direct access to memory.

**Comment by blackmaple** [comment]
I mean why did you hook string format instead of cheating Dyned memory data directly with Win32 API which is called WriteMemoryProcess
